version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static_root
      # - media_volume:/usr/src/app/media_root
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static_root
      # - media_volume:/usr/src/app/media_root
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
volumes:
  static_volume:
  # media_volume:
