# Generated by Django 4.1 on 2023-05-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='관 이름')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='관 소개')),
                ('congest_lv', models.CharField(blank=True, max_length=30, null=True, verbose_name='혼잡도')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='시설명')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='시설 소개')),
                ('addr', models.CharField(max_length=200, verbose_name='주소')),
                ('internet_addr', models.CharField(max_length=200, verbose_name='홈페이지 주소')),
                ('phone_num', models.CharField(max_length=30, verbose_name='전화번호')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('congest_lv', models.CharField(max_length=30)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cctv.building')),
            ],
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(max_length=200, verbose_name='촬영 범위')),
                ('computed_congest_lv', models.CharField(blank=True, max_length=30, null=True, verbose_name='계산된 혼잡도')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.facility'),
        ),
    ]
