# Generated by Django 4.1 on 2023-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctv',
            name='computed_congest_lv',
        ),
        migrations.RemoveField(
            model_name='cctv',
            name='coverage',
        ),
        migrations.AddField(
            model_name='cctv',
            name='base',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BASE 영역(픽셀)'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='rt_base',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='실시간 바닥 영역'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RTSP URL'),
        ),
    ]
