# Generated by Django 4.1 on 2023-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_remove_cctv_computed_congest_lv_remove_cctv_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctv',
            name='base',
        ),
        migrations.AddField(
            model_name='building',
            name='base',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BASE 영역(픽셀)'),
        ),
    ]
